[[tests]]
name = "test1"
input = ["./rarray", "1"]
expected = """
cap: 0
size: 0
"""
rubric = 10

[[tests]]
name = "test2"
input = ["./rarray", "2", "1", "2", "3"]
expected = """
size: 3
1
2
3
"""
rubric = 10

[[tests]]
name = "test3"
input = ["./rarray", "3", "100", "200", "300"]
expected = """
100
"""
rubric = 10

[[tests]]
name = "test4"
input = ["./rarray", "4", "2", "4", "6", "8"]
expected = """
4
6
8
"""
rubric = 10

[[tests]]
name = "test5"
input = ["./rarray", "5", "1", "3", "2", "4", "9", "6", "8", "7", "5"]
expected = """
9
8
7
6
5
4
3
2
1
"""
rubric = 10

[[tests]]
name = "path_only"
input = ["./$project", "$project_tests/0"]
expected = """
$project_tests/0/0.txt 12
$project_tests/0/1/1.txt 1251
$project_tests/0/1/2/2.txt 39
"""
rubric = 20

[[tests]]
name = "sorted"
input = ["./$project", "-s", "$project_tests/0"]
expected = """
$project_tests/0/1/1.txt 1251
$project_tests/0/1/2/2.txt 39
$project_tests/0/0.txt 12
"""
rubric = 15

[[tests]]
name = "limit"
input = ["./$project", "-s", "-l", "1", "$project_tests/0"]
expected = """
$project_tests/0/1/1.txt 1251
"""
rubric = 15

